import type {
  Zone,
  Project,
  AlertItem,
  Report,
  HistoryPoint,
  ActivityEntry,
  PillarDef,
} from "@/types";

export const ZONES: Zone[] = [
  { id: "westlands", name: "Westlands", score: 76, pillars: { social: 82, safety: 71, density: 64, infra: 80 }, deltas: { social: 3, safety: -1, density: 2, infra: 4 }, centroid: [36.8048, -1.2673], lastSyncMin: 4 },
  { id: "dagoretti-north", name: "Dagoretti North", score: 72, pillars: { social: 74, safety: 68, density: 70, infra: 66 }, deltas: { social: 2, safety: 1, density: -2, infra: 3 }, centroid: [36.7600, -1.2750], lastSyncMin: 7 },
  { id: "dagoretti-south", name: "Dagoretti South", score: 65, pillars: { social: 62, safety: 64, density: 60, infra: 68 }, deltas: { social: 1, safety: -3, density: 2, infra: 1 }, centroid: [36.7450, -1.3050], lastSyncMin: 12 },
  { id: "langata", name: "Langata", score: 70, pillars: { social: 72, safety: 74, density: 55, infra: 71 }, deltas: { social: -1, safety: 2, density: 1, infra: 3 }, centroid: [36.7350, -1.3600], lastSyncMin: 5 },
  { id: "kibra", name: "Kibra", score: 54, pillars: { social: 48, safety: 52, density: 58, infra: 56 }, deltas: { social: 2, safety: -2, density: 1, infra: 0 }, centroid: [36.7850, -1.3150], lastSyncMin: 18 },
  { id: "roysambu", name: "Roysambu", score: 68, pillars: { social: 70, safety: 65, density: 62, infra: 72 }, deltas: { social: 1, safety: 3, density: -1, infra: 2 }, centroid: [36.8750, -1.2200], lastSyncMin: 9 },
  { id: "kasarani", name: "Kasarani", score: 63, pillars: { social: 60, safety: 62, density: 58, infra: 68 }, deltas: { social: -1, safety: 2, density: 0, infra: 1 }, centroid: [36.9000, -1.2350], lastSyncMin: 6 },
  { id: "ruaraka", name: "Ruaraka", score: 66, pillars: { social: 68, safety: 64, density: 60, infra: 70 }, deltas: { social: 2, safety: 0, density: -1, infra: 3 }, centroid: [36.8800, -1.2500], lastSyncMin: 11 },
  { id: "embakasi-south", name: "Embakasi South", score: 58, pillars: { social: 55, safety: 56, density: 62, infra: 58 }, deltas: { social: 1, safety: -1, density: 2, infra: 0 }, centroid: [36.9100, -1.3300], lastSyncMin: 14 },
  { id: "embakasi-north", name: "Embakasi North", score: 62, pillars: { social: 60, safety: 64, density: 56, infra: 66 }, deltas: { social: 0, safety: 2, density: 1, infra: -1 }, centroid: [36.9050, -1.2800], lastSyncMin: 8 },
  { id: "embakasi-central", name: "Embakasi Central", score: 60, pillars: { social: 58, safety: 60, density: 54, infra: 64 }, deltas: { social: 1, safety: 1, density: -2, infra: 2 }, centroid: [36.8900, -1.3100], lastSyncMin: 10 },
  { id: "embakasi-east", name: "Embakasi East", score: 76, pillars: { social: 78, safety: 72, density: 70, infra: 82 }, deltas: { social: 4, safety: 2, density: 1, infra: 5 }, centroid: [36.9300, -1.2900], lastSyncMin: 3 },
  { id: "embakasi-west", name: "Embakasi West", score: 61, pillars: { social: 58, safety: 62, density: 56, infra: 66 }, deltas: { social: -1, safety: 1, density: 0, infra: 2 }, centroid: [36.8700, -1.3200], lastSyncMin: 15 },
  { id: "makadara", name: "Makadara", score: 64, pillars: { social: 62, safety: 66, density: 58, infra: 68 }, deltas: { social: 2, safety: -1, density: 1, infra: 3 }, centroid: [36.8600, -1.2950], lastSyncMin: 7 },
  { id: "kamukunji", name: "Kamukunji", score: 57, pillars: { social: 54, safety: 52, density: 60, infra: 58 }, deltas: { social: -2, safety: 1, density: 3, infra: 0 }, centroid: [36.8450, -1.2800], lastSyncMin: 20 },
  { id: "starehe", name: "Starehe", score: 69, pillars: { social: 66, safety: 68, density: 72, infra: 70 }, deltas: { social: 1, safety: 2, density: -1, infra: 2 }, centroid: [36.8250, -1.2850], lastSyncMin: 5 },
  { id: "mathare", name: "Mathare", score: 52, pillars: { social: 46, safety: 48, density: 56, infra: 54 }, deltas: { social: -1, safety: -2, density: 1, infra: 0 }, centroid: [36.8580, -1.2580], lastSyncMin: 22 },
];

export const PROJECTS: Project[] = [
  { id: "p1", name: "Waiyaki Way Expansion", zoneId: "westlands", agency: "KeNHA", type: "road", status: "active", progress: 72, budget: "KES 1.2B", started: "2025-01-15", eta: "2026-06-30", milestones: [{ date: "2025-01-15", label: "Groundbreaking", done: true }, { date: "2025-06-01", label: "Phase 1 paving", done: true }, { date: "2025-12-01", label: "Interchange complete", done: true }, { date: "2026-03-15", label: "Lane markings", done: false }, { date: "2026-06-30", label: "Final inspection", done: false }], marker: [36.7950, -1.2650] },
  { id: "p2", name: "Thika Road Smart Lighting", zoneId: "kasarani", agency: "KPLC", type: "energy", status: "active", progress: 45, budget: "KES 340M", started: "2025-04-01", eta: "2026-02-28", milestones: [{ date: "2025-04-01", label: "Contract signed", done: true }, { date: "2025-08-15", label: "Pole installation", done: true }, { date: "2025-12-01", label: "Wiring phase", done: false }, { date: "2026-02-28", label: "Commissioning", done: false }], marker: [36.8950, -1.2200] },
  { id: "p3", name: "Inner Ring Resurfacing", zoneId: "starehe", agency: "KURA", type: "road", status: "stalled", progress: 34, budget: "KES 180M", started: "2025-02-10", eta: "2025-11-30", milestones: [{ date: "2025-02-10", label: "Mobilization", done: true }, { date: "2025-05-01", label: "Milling", done: true }, { date: "2025-08-01", label: "Overlay", done: false }, { date: "2025-11-30", label: "Completion", done: false }], marker: [36.8300, -1.2900] },
  { id: "p4", name: "Embakasi Substation Upgrade", zoneId: "embakasi-east", agency: "KETRACO", type: "grid", status: "active", progress: 88, budget: "KES 520M", started: "2024-09-01", eta: "2026-01-15", milestones: [{ date: "2024-09-01", label: "Design approval", done: true }, { date: "2025-01-15", label: "Transformer delivery", done: true }, { date: "2025-06-01", label: "Installation", done: true }, { date: "2025-10-01", label: "Testing", done: true }, { date: "2026-01-15", label: "Grid connection", done: false }], marker: [36.9250, -1.2850] },
  { id: "p5", name: "Langata Road Dualling", zoneId: "langata", agency: "KeNHA", type: "road", status: "active", progress: 61, budget: "KES 890M", started: "2025-03-01", eta: "2026-09-30", milestones: [{ date: "2025-03-01", label: "Groundbreaking", done: true }, { date: "2025-07-15", label: "Earthworks", done: true }, { date: "2025-12-01", label: "Base course", done: true }, { date: "2026-05-01", label: "Asphalt", done: false }, { date: "2026-09-30", label: "Handover", done: false }], marker: [36.7400, -1.3500] },
  { id: "p6", name: "Roysambu Solar Microgrid", zoneId: "roysambu", agency: "KPLC", type: "energy", status: "active", progress: 55, budget: "KES 240M", started: "2025-05-15", eta: "2026-04-30", milestones: [{ date: "2025-05-15", label: "Site survey", done: true }, { date: "2025-09-01", label: "Panel installation", done: true }, { date: "2026-01-15", label: "Battery storage", done: false }, { date: "2026-04-30", label: "Go-live", done: false }], marker: [36.8800, -1.2150] },
  { id: "p7", name: "Eastleigh Fibre Backbone", zoneId: "kamukunji", agency: "ICTA", type: "grid", status: "active", progress: 40, budget: "KES 160M", started: "2025-06-01", eta: "2026-05-31", milestones: [{ date: "2025-06-01", label: "Route survey", done: true }, { date: "2025-10-01", label: "Trenching", done: true }, { date: "2026-02-01", label: "Fibre laying", done: false }, { date: "2026-05-31", label: "Activation", done: false }], marker: [36.8500, -1.2750] },
  { id: "p8", name: "Kibra Access Roads", zoneId: "kibra", agency: "KURA", type: "road", status: "active", progress: 28, budget: "KES 95M", started: "2025-07-01", eta: "2026-06-30", milestones: [{ date: "2025-07-01", label: "Community engagement", done: true }, { date: "2025-11-01", label: "Drainage", done: false }, { date: "2026-03-01", label: "Paving", done: false }, { date: "2026-06-30", label: "Completion", done: false }], marker: [36.7900, -1.3100] },
  { id: "p9", name: "Mathare Distribution Line", zoneId: "mathare", agency: "KPLC", type: "energy", status: "planned", progress: 8, budget: "KES 120M", started: "2026-01-15", eta: "2026-12-31", milestones: [{ date: "2026-01-15", label: "Feasibility study", done: true }, { date: "2026-04-01", label: "Design phase", done: false }, { date: "2026-08-01", label: "Construction", done: false }, { date: "2026-12-31", label: "Energization", done: false }], marker: [36.8600, -1.2550] },
  { id: "p10", name: "Makadara Smart Grid Pilot", zoneId: "makadara", agency: "KETRACO", type: "grid", status: "active", progress: 67, budget: "KES 310M", started: "2025-02-01", eta: "2026-03-31", milestones: [{ date: "2025-02-01", label: "Meter procurement", done: true }, { date: "2025-06-15", label: "Installation phase 1", done: true }, { date: "2025-11-01", label: "Installation phase 2", done: true }, { date: "2026-03-31", label: "Full deployment", done: false }], marker: [36.8650, -1.2980] },
  { id: "p11", name: "Kibra Communal Water Kiosks", zoneId: "kibra", agency: "NCWSC", type: "water", status: "active", progress: 42, budget: "KES 85M", started: "2025-06-01", eta: "2026-08-31", milestones: [{ date: "2025-06-01", label: "Community water-point mapping", done: true }, { date: "2025-09-15", label: "Borehole drilling & yield test", done: true }, { date: "2026-01-15", label: "Kiosk construction (14 sites)", done: false }, { date: "2026-05-01", label: "Metered distribution network", done: false }, { date: "2026-08-31", label: "Commissioning & tariff setup", done: false }], marker: [36.7820, -1.3180] },
  { id: "p12", name: "Mathare DEWATS Sanitation Block", zoneId: "mathare", agency: "Athi Water Works", type: "water", status: "active", progress: 35, budget: "KES 68M", started: "2025-08-01", eta: "2026-10-31", milestones: [{ date: "2025-08-01", label: "Site survey & flood-line study", done: true }, { date: "2025-11-01", label: "Community engagement & siting", done: true }, { date: "2026-03-01", label: "Ablution block construction", done: false }, { date: "2026-07-01", label: "Biodigester & DEWATS install", done: false }, { date: "2026-10-31", label: "Handover to sanitation SACCO", done: false }], marker: [36.8550, -1.2600] },
  { id: "p13", name: "Dagoretti South Water Main Extension", zoneId: "dagoretti-south", agency: "NCWSC", type: "water", status: "active", progress: 58, budget: "KES 140M", started: "2025-04-15", eta: "2026-05-31", milestones: [{ date: "2025-04-15", label: "Route survey & wayleave", done: true }, { date: "2025-08-01", label: "Trenching (6.2 km)", done: true }, { date: "2025-12-15", label: "DN300 pipe laying", done: false }, { date: "2026-03-15", label: "Pressure testing", done: false }, { date: "2026-05-31", label: "Zonal connection & flush", done: false }], marker: [36.7480, -1.3020] },
  { id: "p14", name: "Embakasi Faecal Sludge Treatment Plant", zoneId: "embakasi-south", agency: "Athi Water Works", type: "water", status: "planned", progress: 12, budget: "KES 310M", started: "2026-02-01", eta: "2027-03-31", milestones: [{ date: "2026-02-01", label: "Feasibility & catchment study", done: true }, { date: "2026-05-01", label: "ESIA & NEMA licensing", done: false }, { date: "2026-09-01", label: "Land acquisition (4 ha)", done: false }, { date: "2027-01-15", label: "Plant construction", done: false }, { date: "2027-03-31", label: "Commissioning (400 m³/day)", done: false }], marker: [36.9130, -1.3270] },
  { id: "p15", name: "Ruaraka Bypass Rehabilitation", zoneId: "ruaraka", agency: "KURA", type: "road", status: "active", progress: 53, budget: "KES 420M", started: "2025-05-01", eta: "2026-07-31", milestones: [{ date: "2025-05-01", label: "Mobilization", done: true }, { date: "2025-09-01", label: "Culvert & drainage works", done: true }, { date: "2026-01-15", label: "Base & binder course", done: false }, { date: "2026-05-01", label: "Asphalt overlay", done: false }, { date: "2026-07-31", label: "Road marking & handover", done: false }], marker: [36.8830, -1.2470] },
  { id: "p16", name: "Dagoretti North Fibre Ring", zoneId: "dagoretti-north", agency: "ICTA", type: "grid", status: "active", progress: 47, budget: "KES 130M", started: "2025-06-15", eta: "2026-06-30", milestones: [{ date: "2025-06-15", label: "Route survey", done: true }, { date: "2025-10-01", label: "Duct & manhole works", done: true }, { date: "2026-02-01", label: "Fibre blowing", done: false }, { date: "2026-06-30", label: "Node activation", done: false }], marker: [36.7630, -1.2720] },
  { id: "p17", name: "Embakasi North Feeder Line", zoneId: "embakasi-north", agency: "KPLC", type: "energy", status: "active", progress: 64, budget: "KES 280M", started: "2025-03-15", eta: "2026-04-30", milestones: [{ date: "2025-03-15", label: "Design & wayleave", done: true }, { date: "2025-07-01", label: "Pole & conductor stringing", done: true }, { date: "2025-12-01", label: "Transformer bays", done: true }, { date: "2026-04-30", label: "Energization", done: false }], marker: [36.9080, -1.2770] },
  { id: "p18", name: "Jogoo Road Corridor Upgrade", zoneId: "embakasi-central", agency: "KURA", type: "road", status: "stalled", progress: 31, budget: "KES 360M", started: "2025-02-20", eta: "2026-03-31", milestones: [{ date: "2025-02-20", label: "Mobilization", done: true }, { date: "2025-06-01", label: "Utility relocation", done: true }, { date: "2025-10-01", label: "Carriageway widening", done: false }, { date: "2026-03-31", label: "Non-motorized transport lanes", done: false }], marker: [36.8930, -1.3070] },
  { id: "p19", name: "Embakasi West Solar Streetlights", zoneId: "embakasi-west", agency: "KPLC", type: "energy", status: "active", progress: 49, budget: "KES 190M", started: "2025-07-01", eta: "2026-05-31", milestones: [{ date: "2025-07-01", label: "Site audit & spacing plan", done: true }, { date: "2025-11-15", label: "Foundation & pole erection", done: true }, { date: "2026-02-15", label: "Solar head & battery mount", done: false }, { date: "2026-05-31", label: "Network commissioning", done: false }], marker: [36.8730, -1.3170] },
];

export const ALERTS: AlertItem[] = [
  {
    id: "a1", severity: "high", kind: "infra", title: "Inner Ring Resurfacing stalled", body: "Contractor has not mobilized equipment for 45 days. KURA issued a show-cause notice on May 10. Project timeline at risk.", zoneId: "starehe", createdAt: "2026-05-20T09:30:00Z", read: false,
    affectedInfra: ["Inner Ring Road", "CBD access routes", "Public transit corridors"],
    recommendedActions: [
      "Issue formal notice to contractor within 48 hours",
      "Activate penalty clause (Section 12.3 of contract)",
      "Prepare alternative contractor shortlist",
      "Notify affected commuters via county channels",
    ],
    impactLevel: "critical",
    relatedProjectIds: ["p3"],
  },
  {
    id: "a2", severity: "medium", kind: "vitality", title: "Kibra safety score dropped 4 pts", body: "Safety & Security pillar for Kibra fell from 56 to 52 following two reported infrastructure vandalism incidents in April.", zoneId: "kibra", createdAt: "2026-05-18T14:00:00Z", read: false,
    affectedInfra: ["Kibra Access Roads", "Street lighting network", "Community water points"],
    recommendedActions: [
      "Deploy community surveillance patrols at vandalism hotspots",
      "Fast-track solar-powered lighting installation along access roads",
      "Coordinate with National Police Service for increased presence",
      "Engage community leaders through ward-level forums",
    ],
    impactLevel: "major",
    relatedProjectIds: ["p8"],
  },
  {
    id: "a3", severity: "low", kind: "esia", title: "ESIA published for Mathare Distribution Line", body: "Environmental and Social Impact Assessment for the Mathare Distribution Line project is now publicly available on the NEMA portal.", zoneId: "mathare", createdAt: "2026-05-15T11:00:00Z", read: false,
    affectedInfra: ["Mathare Distribution Line", "Existing 11kV overhead lines", "Juja Road transformer station"],
    recommendedActions: [
      "Review ESIA findings and flag any community resettlement requirements",
      "Verify compliance with NEMA conditions of approval",
      "Schedule public participation session within 30 days",
    ],
    impactLevel: "minor",
    relatedProjectIds: ["p9"],
  },
  {
    id: "a4", severity: "high", kind: "system", title: "KPLC data feed interrupted", body: "The automated feed from Kenya Power has not delivered updates in 72 hours. Energy layer data may be stale for affected zones.", zoneId: null, createdAt: "2026-05-22T07:15:00Z", read: false,
    affectedInfra: ["Thika Road Smart Lighting", "Roysambu Solar Microgrid", "Makadara Smart Grid Pilot", "Mathare Distribution Line"],
    recommendedActions: [
      "Contact KPLC data liaison to diagnose feed failure",
      "Switch to backup manual data-entry pipeline for critical zones",
      "Flag all energy-layer scores as provisional until feed restores",
      "Notify downstream report consumers of potential data staleness",
      "Escalate to KPLC regional manager if unresolved within 24 hours",
    ],
    impactLevel: "major",
    relatedProjectIds: ["p2", "p6", "p9", "p10"],
  },
  {
    id: "a5", severity: "medium", kind: "partner", title: "Nairobi County GIS unit MOU signed", body: "Letter of intent signed with Nairobi County GIS unit for pilot data sharing. Integration timeline TBD.", zoneId: null, createdAt: "2026-05-12T16:30:00Z", read: true,
    affectedInfra: ["County GIS data pipeline", "Zoning boundary datasets", "Land-use registry"],
    recommendedActions: [
      "Schedule technical integration workshop with county GIS team",
      "Define data format and API specifications for shared feeds",
      "Establish data-sharing governance protocol aligned with KDPA",
      "Set quarterly review milestones for data quality assessment",
    ],
    impactLevel: "moderate",
    relatedProjectIds: [],
  },
  {
    id: "a6", severity: "low", kind: "vitality", title: "Embakasi East tops leaderboard", body: "Embakasi East has overtaken Westlands for the highest overall Vitality score (76) following infrastructure upgrades at the KETRACO substation.", zoneId: "embakasi-east", createdAt: "2026-05-10T10:00:00Z", read: true,
    affectedInfra: ["Embakasi Substation", "KETRACO 132kV transmission line", "Local distribution network"],
    recommendedActions: [
      "Document Embakasi East as a case study for replication in other zones",
      "Share success metrics with KETRACO for joint communications",
      "Assess whether substation model can be adapted for Embakasi West",
    ],
    impactLevel: "minor",
    relatedProjectIds: ["p4"],
  },
  {
    id: "a7", severity: "high", kind: "infra", title: "Kibra water kiosk borehole yield below projection", body: "Yield testing on the Kibra Communal Water Kiosks borehole returned 8.4 m³/hr against a design assumption of 14 m³/hr. At current yield the 14-kiosk network cannot meet peak demand for the 185,000 residents, and average wait times would stay above the 15-minute target.", zoneId: "kibra", createdAt: "2026-05-23T08:45:00Z", read: false,
    affectedInfra: ["Kibra Communal Water Kiosks", "Shared water points (62% of households)", "Metered distribution network"],
    recommendedActions: [
      "Commission a second borehole or bulk-water connection from the Ngong trunk main",
      "Right-size the kiosk network to the verified yield before construction proceeds",
      "Introduce off-peak storage tanks to buffer demand and cut wait times",
      "Re-run the demand model with NCWSC using verified yield figures",
    ],
    impactLevel: "major",
    relatedProjectIds: ["p11"],
  },
  {
    id: "a8", severity: "medium", kind: "esia", title: "Embakasi FSTP public participation opens", body: "The Environmental & Social Impact Assessment for the Embakasi Faecal Sludge Treatment Plant is open for public comment on the NEMA portal until June 20. The plant would give informal settlements a decentralized alternative to conventional sewerage, which is not viable at Embakasi's density and cost.", zoneId: "embakasi-south", createdAt: "2026-05-21T12:00:00Z", read: false,
    affectedInfra: ["Embakasi Faecal Sludge Treatment Plant", "Exhauster-truck disposal routes", "Nairobi River discharge points"],
    recommendedActions: [
      "Mobilize community input during the public participation window",
      "Verify buffer distances from the nearest residential cluster (4 ha site)",
      "Confirm faecal-sludge feedstock volumes with licensed exhauster operators",
      "Align the treatment standard with the Kenya effluent discharge regulations",
    ],
    impactLevel: "moderate",
    relatedProjectIds: ["p14"],
  },
  {
    id: "a9", severity: "high", kind: "vitality", title: "Mathare sanitation coverage critically low", body: "Baseline survey confirms only 11% of Mathare households have access to a safely managed sanitation facility. With the valley's flood risk and informal layout, conventional sewered toilets are not deliverable — the DEWATS sanitation block is the primary intervention but is only 35% complete.", zoneId: "mathare", createdAt: "2026-05-19T09:15:00Z", read: false,
    affectedInfra: ["Mathare DEWATS Sanitation Block", "Riverine pit latrines", "Mathare River water quality"],
    recommendedActions: [
      "Accelerate the DEWATS ablution-block construction phase",
      "Deploy interim container-based sanitation units during the long rains",
      "Establish a community sanitation SACCO to run the block after handover",
      "Test Mathare River downstream for faecal contamination as a baseline",
    ],
    impactLevel: "critical",
    relatedProjectIds: ["p12"],
  },
  {
    id: "a10", severity: "medium", kind: "infra", title: "Dagoretti South water main trench flooding", body: "Long-rains flooding has submerged 1.8 km of open trench on the Dagoretti South Water Main Extension, halting DN300 pipe laying. The project remains at 58% and the May 31 zonal-connection milestone is now at risk.", zoneId: "dagoretti-south", createdAt: "2026-05-17T15:30:00Z", read: false,
    affectedInfra: ["Dagoretti South Water Main Extension", "Open trench (1.8 km)", "Ngong Road service reservoir"],
    recommendedActions: [
      "Deploy dewatering pumps and shore up trench walls before resuming",
      "Re-sequence pipe laying to elevated dry sections first",
      "Revise the connection milestone to account for weather delay",
      "Add temporary drainage to protect the remaining open trench",
    ],
    impactLevel: "moderate",
    relatedProjectIds: ["p13"],
  },
  {
    id: "a11", severity: "low", kind: "partner", title: "Athi Water co-financing agreement signed", body: "Athi Water Works Development Agency has signed a co-financing agreement covering the Mathare DEWATS block and the Embakasi Faecal Sludge Treatment Plant, unlocking KES 210M in matched sanitation funding under the SDG-6 acceleration window.", zoneId: null, createdAt: "2026-05-14T11:30:00Z", read: true,
    affectedInfra: ["Mathare DEWATS Sanitation Block", "Embakasi Faecal Sludge Treatment Plant", "County sanitation budget line"],
    recommendedActions: [
      "Formalize disbursement milestones tied to construction progress",
      "Map both projects into the county SDG-6 monitoring framework",
      "Schedule a joint quarterly review with Athi Water and NCWSC",
    ],
    impactLevel: "minor",
    relatedProjectIds: ["p12", "p14"],
  },
  {
    id: "a12", severity: "high", kind: "infra", title: "Jogoo Road corridor upgrade stalled", body: "The Jogoo Road Corridor Upgrade has been stalled at 31% for over a month after a utility-relocation dispute with a fibre operator. Non-motorized transport lanes and carriageway widening are both on hold, and Embakasi Central's density pillar is exposed.", zoneId: "embakasi-central", createdAt: "2026-05-16T10:20:00Z", read: false,
    affectedInfra: ["Jogoo Road Corridor Upgrade", "Buried fibre & water reticulation", "Non-motorized transport lanes"],
    recommendedActions: [
      "Convene KURA, the fibre operator, and NCWSC to resolve the wayleave clash",
      "Escalate the utility-relocation dispute to the county infrastructure committee",
      "Publish a revised programme once relocation responsibility is agreed",
      "Secure the idle site to prevent equipment and material loss",
    ],
    impactLevel: "major",
    relatedProjectIds: ["p18"],
  },
];

export const REPORTS: Report[] = [
  {
    id: "r1",
    title: "Nairobi Q1 2026 Vitality Report",
    zoneId: null,
    date: "2026-04-15",
    status: "published",
    author: "Ken N'ganga",
    sizeBytes: 2_450_000,
    format: "PDF",
    type: "vitality",
    priority: "high",
    tags: ["quarterly", "county-wide", "vitality-index", "baseline"],
    pillarFocus: ["social", "safety", "density", "infra"],
    dateRange: { from: "2026-01-01", to: "2026-03-31" },
    executiveSummary: "Comprehensive quarterly assessment of Nairobi County's readiness across all 17 sub-county zones. The county-wide Vitality Index rose from 61.0 to 65.8 over Q1, driven primarily by infrastructure upgrades in Embakasi East and Westlands. Kibra and Mathare remain below the 60-point threshold, requiring targeted interventions in safety and social wellbeing pillars.",
    sections: [
      { heading: "Methodology", content: "Scores computed using the UE Vitality Index v1.2 framework across four pillars: Social Wellbeing & Human Capital, Safety & Security, Density & Scaling Dynamics, and Infrastructure & Environmental Safeguards. Data sourced from KNBS, KURA, KPLC, KETRACO, and NEMA feeds aggregated between January 1 and March 31, 2026." },
      { heading: "County-Wide Trends", content: "The overall county average climbed 4.8 points to 65.8 — the strongest quarterly gain since tracking began. Embakasi East led all zones with a 6-point jump following the KETRACO substation upgrade reaching 88% completion.\nWestlands maintained its position as the highest-scoring zone (76), though its growth rate slowed as major road works on Waiyaki Way entered the lane-marking phase.\nThe bottom quartile (Kibra 54, Mathare 52, Kamukunji 57) showed mixed movement — Kibra's safety score dropped 4 points after two vandalism incidents." },
      { heading: "Pillar Breakdown", content: "Social Wellbeing (county avg 62.4): Marginal gains in workforce mobility offset by stagnant healthcare access in informal settlements.\nSafety & Security (county avg 63.1): Rule-of-law indicators stable; physical security degraded in Kibra and Mathare.\nDensity & Scaling (county avg 60.8): Urban friction worsened along Thika Road corridor due to ongoing construction.\nInfra & Environmental (county avg 67.2): Strongest pillar — driven by ESIA transparency improvements and the Embakasi substation nearing completion." },
      { heading: "Risk Flags", content: "Inner Ring Resurfacing (Starehe) has stalled for 45+ days — KURA issued a show-cause notice. If unresolved, Starehe's infra pillar could drop 5-8 points next quarter.\nKPLC data feed interrupted for 72 hours in late May — energy layer scores should be treated as provisional until feed restores." },
      { heading: "Recommendations", content: "1. Prioritize safety interventions in Kibra: solar lighting along access roads, community surveillance patrols.\n2. Escalate Inner Ring contractor situation — activate penalty clause if no mobilization within 2 weeks.\n3. Establish redundant data pipeline for KPLC feed to prevent future outages.\n4. Commission detailed density study for Thika Road corridor ahead of smart lighting completion." },
    ],
  },
  {
    id: "r2",
    title: "Westlands Infrastructure Assessment",
    zoneId: "westlands",
    date: "2026-05-01",
    status: "published",
    author: "Devyan Jethwa",
    sizeBytes: 1_820_000,
    format: "PDF",
    type: "infrastructure",
    priority: "medium",
    tags: ["infrastructure", "road-progress", "smart-grid", "westlands"],
    pillarFocus: ["infra"],
    dateRange: { from: "2026-01-01", to: "2026-04-30" },
    executiveSummary: "Westlands maintains the highest Vitality score in Nairobi (76) supported by strong infrastructure delivery. The Waiyaki Way Expansion is 72% complete with Phase 2 paving ahead of schedule. Smart meter rollout has reached 1,200 units in Parklands. Key risk: lane-marking phase requires full weekend road closures that may impact the Urban Friction Index.",
    sections: [
      { heading: "Active Projects Summary", content: "Waiyaki Way Expansion (KeNHA): 72% complete, KES 1.2B budget. Groundbreaking, Phase 1 paving, and interchange completed on schedule. Lane markings and final inspection remain.\nSmart Meter Rollout (KPLC): 1,200 units deployed in Parklands sub-area. Coverage target is 3,500 units by end of 2026." },
      { heading: "Infrastructure Pillar Deep Dive", content: "ESIA Transparency: Updated assessment for Westlands commercial zone published May 18 via NEMA portal. Full compliance with KDPA requirements.\nResource Sovereignty: Water rights stable; no contestation on current grid expansion permits.\nCircular Economy: Two construction firms operating in the zone now use 30% recycled aggregate — a first for Nairobi." },
      { heading: "Density Impact", content: "Population density survey (KNBS, Q1 2026) shows a 2.1% increase in Westlands — primarily commercial daytime population. The Optimal Density Ratio remains healthy at 1.12, but weekend road closures for lane-marking could push the Urban Friction Index above threshold temporarily." },
      { heading: "Outlook", content: "Westlands is on track to exceed a Vitality score of 78 by Q3 if current project timelines hold. The primary downside risk is construction-related traffic disruption during the Waiyaki Way lane-marking phase scheduled for June-July." },
    ],
  },
  {
    id: "r3",
    title: "Kibra Urban Density Analysis",
    zoneId: "kibra",
    date: "2026-05-10",
    status: "review",
    author: "Joy Nthei",
    sizeBytes: 980_000,
    format: "PDF",
    type: "density",
    priority: "high",
    tags: ["density", "informal-settlement", "kibra", "urban-planning"],
    pillarFocus: ["density", "social"],
    dateRange: { from: "2025-10-01", to: "2026-04-30" },
    executiveSummary: "Kibra's Optimal Density Ratio stands at 0.68 — well below the healthy threshold of 1.0. Infrastructure capacity has not kept pace with population growth, creating compounding pressure on access roads, water points, and the electrical distribution network. The Kibra Access Roads project (28% complete) is the single largest intervention, but its current pace will not close the gap before density pressures trigger service failures.",
    sections: [
      { heading: "Population & Density Metrics", content: "Estimated population: 185,000 (KNBS Q1 2026 projection). Area: 2.35 km². Density: 78,723 persons/km² — highest in Nairobi County.\nThe Optimal Density Ratio (Infrastructure Capacity / Population Density) fell from 0.72 to 0.68 over the past two quarters, indicating infrastructure is losing ground relative to population." },
      { heading: "Infrastructure Capacity Assessment", content: "Roads: Only 34% of internal roads are paved. The Kibra Access Roads project (KURA, KES 95M) is at 28% completion — community engagement done, drainage phase not yet started.\nWater: 62% of households rely on shared water points. Average wait time increased from 22 to 31 minutes in Q1.\nElectricity: Informal connections account for an estimated 40% of supply. KPLC has no scheduled upgrade for the area." },
      { heading: "Social Wellbeing Intersection", content: "High density with low infrastructure drives down the Social Wellbeing pillar (48). Access to amenities, healthcare facilities, and green space are all below county averages. Mental Health & Livability sub-metric is the lowest in Nairobi at 38." },
      { heading: "Recommendations", content: "1. Accelerate Kibra Access Roads drainage phase — current 28% pace risks missing the 2026 completion target.\n2. Pilot a decentralized water kiosk network to reduce wait times below 15 minutes.\n3. Coordinate with KPLC on a dedicated distribution line for Kibra — the current informal connection rate is a safety hazard.\n4. Designate at least two community green spaces as part of the access roads project scope." },
    ],
  },
  {
    id: "r4",
    title: "Embakasi Substation Impact Study",
    zoneId: "embakasi-east",
    date: "2026-05-18",
    status: "review",
    author: "Khillon",
    sizeBytes: 1_540_000,
    format: "PDF",
    type: "infrastructure",
    priority: "critical",
    tags: ["energy", "substation", "KETRACO", "embakasi-east", "grid"],
    pillarFocus: ["infra", "safety"],
    dateRange: { from: "2024-09-01", to: "2026-05-15" },
    executiveSummary: "The Embakasi Substation Upgrade (KETRACO, KES 520M) is 88% complete — transformer testing finished successfully on May 21. Grid connection is the final milestone. This project has been the primary driver of Embakasi East's rise to joint-highest Vitality score (76). The study assesses downstream impacts on surrounding zones and identifies risks associated with the final connection phase.",
    sections: [
      { heading: "Project Timeline & Status", content: "Design approval (Sep 2024): Complete\nTransformer delivery (Jan 2025): Complete\nInstallation (Jun 2025): Complete\nTesting (Oct 2025): Complete — all load tests passed within tolerance\nGrid connection (Jan 2026 target): Pending — delayed to estimated July 2026 due to KPLC coordination issues" },
      { heading: "Vitality Impact Analysis", content: "Embakasi East's Infrastructure & Environmental Safeguards pillar rose from 64 to 82 since project inception — the largest single-project pillar gain recorded in the Atlas.\nSafety & Security pillar also improved (+8 points) as the substation's physical security perimeter displaced informal dumping and reduced crime in the immediate area.\nThe zone overtook Westlands as joint-highest scorer (76) in May 2026." },
      { heading: "Downstream Effects", content: "Embakasi North: Expected 3-5 point infra pillar gain once grid connection enables load redistribution.\nEmbakasi Central: May see reduced outage frequency — currently averaging 4.2 unplanned outages/month.\nEmbakasi West: Minimal direct benefit; the 66kV feeder does not extend to the western boundary." },
      { heading: "Risk Assessment", content: "Grid connection delay: KPLC coordination has pushed the final milestone back ~6 months. If the 72-hour data feed interruption (Alert a4) is symptomatic of deeper KPLC integration issues, further delays are possible.\nSovereign Immunity: KETRACO operates under government indemnity — any contract breach claims during connection would face sovereign immunity barriers.\nEnvironmental: ESIA conditions met; NEMA clearance on file. No outstanding compliance issues." },
    ],
  },
  {
    id: "r5",
    title: "Mathare Baseline Survey",
    zoneId: "mathare",
    date: "2026-05-20",
    status: "draft",
    author: "Austine Igunza",
    sizeBytes: 640_000,
    format: "PDF",
    type: "vitality",
    priority: "medium",
    tags: ["baseline", "mathare", "informal-settlement", "survey"],
    pillarFocus: ["social", "safety"],
    dateRange: { from: "2026-03-01", to: "2026-05-15" },
    executiveSummary: "Mathare records the lowest Vitality score in Nairobi County (52). This baseline survey establishes ground-truth metrics across all four pillars to serve as a benchmark for future interventions. The Mathare Distribution Line (KPLC, planned) is the only major project in the pipeline. Without additional investment, scores are projected to decline further as population pressure intensifies.",
    sections: [
      { heading: "Zone Profile", content: "Population: ~210,000 (KNBS estimate). Area: 0.95 km². Density: 221,053 persons/km² — second highest in Nairobi after Kibra on a per-area basis, highest in absolute terms.\nThe zone spans the Mathare River valley with significant flood-risk areas. Infrastructure is predominantly informal." },
      { heading: "Pillar Scores & Analysis", content: "Social Wellbeing (46): Lowest in the county. Healthcare access limited to two community clinics. Workforce mobility constrained by poor road network.\nSafety & Security (48): Two homicide incidents in Q1. Street lighting covers only 12% of pathways. Digital sovereignty score N/A — internet penetration below measurement threshold.\nDensity & Scaling (56): Optimal Density Ratio at 0.52 — critical. Every infrastructure metric is saturated.\nInfra & Environmental (54): No active ESIA on file. The Distribution Line ESIA was published May 15 but covers only the transmission corridor, not the broader zone." },
      { heading: "Data Gaps", content: "Workforce Mobility Score: No reliable commute-time data — most residents walk. Proxy metric used (distance to nearest matatu stage).\nDigital Sovereignty: Internet penetration below 15% — sub-metric excluded from score calculation.\nWaste & Lifecycle: No formal waste collection. EPR laws do not apply to informal waste streams." },
      { heading: "Projected Trajectory", content: "Without intervention: score projected to drop to 48-49 by Q4 2026 as density pressure continues.\nWith Distribution Line completion (best case, Dec 2026): infra pillar could gain 8-12 points, lifting overall score to 58-60.\nFull recovery to county average (65) would require coordinated investment across all four pillars — estimated KES 800M+ over 3 years." },
    ],
  },
  {
    id: "r6",
    title: "Nairobi Safety Corridor Mapping",
    zoneId: null,
    date: "2026-05-22",
    status: "draft",
    author: "Ken N'ganga",
    sizeBytes: 420_000,
    format: "PDF",
    type: "safety",
    priority: "high",
    tags: ["safety", "county-wide", "corridors", "crime-mapping", "rule-of-law"],
    pillarFocus: ["safety"],
    executiveSummary: "Preliminary mapping of safety corridors across Nairobi County, cross-referencing the Safety & Security pillar with physical infrastructure routes. Identifies six high-risk transit corridors where infrastructure projects intersect with elevated crime or instability zones. Intended to inform route-level risk scoring for the Atlas layer.",
    sections: [
      { heading: "Scope & Method", content: "Analysis covers the 17 mapped sub-county zones. Safety data sourced from National Police Service quarterly reports (Q4 2025, Q1 2026) and the Atlas Safety & Security pillar sub-metrics. Infrastructure routes from KURA and KeNHA GIS feeds.\nCorridors defined as 500m buffer zones along major roads with active or planned infrastructure projects." },
      { heading: "High-Risk Corridors Identified", content: "1. Kibra Access Road corridor — 3 reported vandalism incidents in 6 months. Equipment theft risk rated HIGH.\n2. Mathare River Road — 2 homicides in Q1. No street lighting. Construction crews require security escort.\n3. Eastleigh (Kamukunji) Fibre Backbone route — petty crime rate 2.4x county average along trenching path.\n4. Inner Ring Road (Starehe) — contractor abandonment zone. Unsecured equipment on-site for 45+ days.\n5. Thika Road (Kasarani) — smart lighting installation exposed to nighttime theft of copper wiring.\n6. Dandora-Pipeline corridor (Embakasi North) — informal settlement encroachment on planned grid route." },
      { heading: "Risk Scoring Framework", content: "Each corridor scored on three axes: crime frequency (NPS data), infrastructure exposure (value of unprotected assets), and lighting coverage (% of corridor with functional street lights).\nProposed integration: overlay corridor risk scores on the Atlas map as a toggleable 'Safety Corridor' sub-layer under the existing Safety & Security pillar." },
      { heading: "Next Steps", content: "This draft requires field verification of corridors 1, 2, and 4 before publication. Coordination with NPS for updated Q2 2026 crime data is pending. Target publication: June 2026." },
    ],
  },
  {
    id: "r7",
    title: "Langata Road Dualling Progress",
    zoneId: "langata",
    date: "2026-04-28",
    status: "published",
    author: "Devyan Jethwa",
    sizeBytes: 1_230_000,
    format: "PDF",
    type: "infrastructure",
    priority: "medium",
    tags: ["road-progress", "langata", "KeNHA", "dualling"],
    pillarFocus: ["infra", "density"],
    dateRange: { from: "2025-03-01", to: "2026-04-28" },
    executiveSummary: "The Langata Road Dualling project (KeNHA, KES 890M) is 61% complete with earthworks and base course finished. The asphalt phase is scheduled for May 2026. Langata's Vitality score (70) is directly supported by this project — the infra pillar gained 3 points this quarter. Key risk: the asphalt phase coincides with the long rains, which historically delays road projects in the area by 3-6 weeks.",
    sections: [
      { heading: "Milestone Status", content: "Groundbreaking (Mar 2025): Complete\nEarthworks (Jul 2025): Complete\nBase course (Dec 2025): Complete\nAsphalt (May 2026): Scheduled — materials procurement confirmed\nHandover (Sep 2026): On track, contingent on weather" },
      { heading: "Budget & Procurement", content: "Total budget: KES 890M. Expenditure to date: KES 548M (61.6%). Remaining committed: KES 342M.\nAsphalt procurement locked at KES 186M through KeNHA framework contract. No cost overrun anticipated unless weather delays exceed 6 weeks." },
      { heading: "Traffic & Density Impact", content: "Current traffic diversion adds 12 minutes average to the Langata-CBD commute. The Urban Friction Index for Langata rose 0.3 points this quarter as a result.\nPost-completion projection: commute time reduction of 8-10 minutes. Density & Scaling pillar expected to gain 4-6 points once dualling is operational." },
      { heading: "Environmental Compliance", content: "ESIA filed and approved (NEMA, Feb 2025). Quarterly monitoring reports submitted on schedule.\nDust suppression measures in place during base course phase. Noise complaints from adjacent residential areas addressed through restricted working hours (7am-6pm).\nNo outstanding compliance issues." },
    ],
  },
  {
    id: "r8",
    title: "Nairobi Water & Sanitation Access Review",
    zoneId: null,
    date: "2026-05-24",
    status: "published",
    author: "Devyan Jethwa",
    sizeBytes: 2_180_000,
    format: "PDF",
    type: "environmental",
    priority: "critical",
    tags: ["sdg-6", "water", "sanitation", "county-wide", "clean-water", "informal-settlements"],
    pillarFocus: ["infra", "social"],
    dateRange: { from: "2026-01-01", to: "2026-05-15" },
    executiveSummary: "A county-wide read on Clean Water & Sanitation (SDG 6) across all 17 Nairobi zones. Safely-managed water access averages 71% county-wide but collapses to 38-46% in the informal settlements of Kibra and Mathare, where conventional sewered sanitation is neither affordable nor physically deliverable. The review argues for a decentralized sanitation strategy — DEWATS blocks, faecal-sludge treatment, and metered communal kiosks — as the context-specific path to closing the gap, and tracks the four active water projects now in delivery.",
    sections: [
      { heading: "Why Conventional Sewerage Falls Short", content: "Nairobi's trunk sewer network reaches roughly 48% of the county population and almost none of the high-density informal settlements. Extending gravity sewers into Kibra and Mathare would require gradients, land corridors, and household connection costs that the settlements' density and tenure simply do not allow.\nThe evidence points to a decentralized model: on-site and cluster-scale treatment (DEWATS), scheduled faecal-sludge emptying to dedicated treatment plants, and metered water kiosks — each sized to the settlement rather than the citywide grid." },
      { heading: "Access Metrics by Zone Band", content: "Established zones (Westlands, Langata, Embakasi East): 78-91% safely-managed water; sewered or septic sanitation adequate.\nPeri-urban zones (Dagoretti South, Kasarani, Ruaraka): 60-72% water access; sanitation mixed, septic-dominant, water-main extensions the key lever.\nInformal settlements (Kibra 44%, Mathare 38%): shared water points serve 62% of Kibra households at a 31-minute average wait; only 11% of Mathare households have safely-managed sanitation. These two zones anchor the county's SDG-6 gap." },
      { heading: "Active Interventions", content: "Kibra Communal Water Kiosks (NCWSC, KES 85M, 42%): 14 metered kiosks targeting sub-15-minute wait times — borehole yield now a live risk (see Alert a7).\nMathare DEWATS Sanitation Block (Athi Water, KES 68M, 35%): decentralized ablution + biodigester block sited above the flood line.\nDagoretti South Water Main Extension (NCWSC, KES 140M, 58%): 6.2 km DN300 main bringing reticulated supply to peri-urban households.\nEmbakasi Faecal Sludge Treatment Plant (Athi Water, KES 310M, planned): 400 m³/day plant giving exhauster operators a licensed disposal point in place of river discharge." },
      { heading: "Sanitation Strategy Recommendations", content: "1. Formalize decentralized sanitation (DEWATS + faecal-sludge management) as the default for informal settlements rather than deferring to sewer extension.\n2. Ring-fence the Athi Water co-financing (KES 210M) to the Mathare and Embakasi sanitation projects.\n3. Pair every water-access project with a sanitation counterpart — kiosks without safe disposal shift the problem downstream.\n4. Stand up a county faecal-sludge management chain: scheduled emptying, licensed transport, and the Embakasi treatment endpoint.\n5. Add downstream Nairobi River water-quality monitoring as the outcome metric for the sanitation programme." },
      { heading: "SDG-6 Outlook", content: "If the four active projects complete on their current envelopes, county safely-managed water access rises an estimated 6-8 points and the two informal-settlement zones gain their first metered supply and decentralized sanitation infrastructure. The binding constraints are borehole yield in Kibra, the long-rains schedule slip in Dagoretti South, and land acquisition for the Embakasi plant." },
    ],
  },
  {
    id: "r9",
    title: "Kibra Decentralized Sanitation Feasibility",
    zoneId: "kibra",
    date: "2026-05-19",
    status: "review",
    author: "Joy Nthei",
    sizeBytes: 1_120_000,
    format: "PDF",
    type: "environmental",
    priority: "high",
    tags: ["sdg-6", "sanitation", "kibra", "dewats", "informal-settlement", "feasibility"],
    pillarFocus: ["infra", "social"],
    dateRange: { from: "2026-02-01", to: "2026-05-15" },
    executiveSummary: "A feasibility assessment for extending decentralized sanitation into Kibra alongside the communal water kiosk programme. With 78,723 persons/km² and no viable sewer corridor, Kibra requires cluster-scale DEWATS and container-based sanitation rather than conventional connections. The study models three delivery options and recommends a phased DEWATS-plus-kiosk pairing anchored to the existing NCWSC water project.",
    sections: [
      { heading: "The Sanitation Gap", content: "Only an estimated 18% of Kibra households have access to a safely-managed toilet. The remainder rely on shared pit latrines, 'flying toilets', or informal connections that discharge into open drains and ultimately the Ngong River.\nThe combination of extreme density, insecure land tenure, and a high water table rules out both household sewer connections and conventional septic tanks at scale." },
      { heading: "Delivery Options Modelled", content: "Option A — Sewer extension: Rejected. Requires household connection costs and land corridors incompatible with the settlement layout; cost per capita 3-4x alternatives.\nOption B — Container-based sanitation (CBS): Low capital, fast to deploy, but depends on a reliable collection logistics chain and ongoing operating subsidy.\nOption C — Cluster DEWATS blocks: Moderate capital, treats waste on-site, pairs naturally with the water-kiosk footprint. Recommended as the primary model, with CBS as an interim and hard-to-reach-cluster supplement." },
      { heading: "Water-Sanitation Pairing", content: "Each of the 14 planned water kiosks anchors a natural service cluster. Siting a DEWATS ablution block at 6-8 of these clusters would give roughly 55% of the settlement a safely-managed option within a 5-minute walk.\nMetered water revenue can cross-subsidize sanitation-block operating costs through a single community SACCO, improving the odds of post-handover sustainability." },
      { heading: "Recommendations", content: "1. Adopt cluster DEWATS as Kibra's primary sanitation model; do not wait on sewer extension.\n2. Co-locate sanitation blocks with the NCWSC water kiosks and operate both under one SACCO.\n3. Pilot container-based sanitation in the two highest-density clusters where even DEWATS siting is constrained.\n4. Resolve the borehole-yield risk first — sanitation blocks need assured water to function.\n5. Sequence Phase 1 (4 blocks) against the kiosk construction milestone to share mobilization costs." },
    ],
  },
  {
    id: "r10",
    title: "Embakasi East Grid Connection Q2 Update",
    zoneId: "embakasi-east",
    date: "2026-05-23",
    status: "published",
    author: "Khillon",
    sizeBytes: 890_000,
    format: "PDF",
    type: "infrastructure",
    priority: "medium",
    tags: ["energy", "grid", "embakasi-east", "KETRACO", "quarterly"],
    pillarFocus: ["infra"],
    dateRange: { from: "2026-04-01", to: "2026-05-23" },
    executiveSummary: "A short-cycle update on the final grid-connection milestone for the Embakasi Substation Upgrade. Testing is complete and the substation is energized on the KETRACO side; the outstanding dependency is KPLC's downstream feeder coordination, currently the pacing item and linked to the wider KPLC data-feed interruption flagged in Alert a4. Connection is now estimated for July 2026.",
    sections: [
      { heading: "Status Since Q1", content: "Transformer load testing closed out on May 21 with all results within tolerance. The substation is live on the transmission side. The only remaining milestone — grid connection — is gated by KPLC feeder works at Embakasi North, not by KETRACO scope." },
      { heading: "KPLC Coordination Risk", content: "The 72-hour KPLC data-feed interruption (Alert a4) coincided with the feeder-coordination delay. While the two may be unrelated, both point to integration friction on the KPLC side. The connection estimate has moved from January to July 2026." },
      { heading: "Downstream Readiness", content: "Once connected, load redistribution should reduce Embakasi Central's unplanned outage rate (currently ~4.2/month) and give Embakasi North's feeder-line project (p17) headroom to energize. Embakasi West sees minimal direct benefit." },
      { heading: "Next Actions", content: "1. Obtain a firm feeder-works date from KPLC regional coordination.\n2. Treat energy-layer scores for the Embakasi cluster as provisional until the KPLC feed stabilizes.\n3. Re-baseline the connection milestone in the Atlas to July 2026." },
    ],
  },
];

export const HISTORY: HistoryPoint[] = [
  { month: "Jun '25", overallAvg: 61 },
  { month: "Jul '25", overallAvg: 61.5 },
  { month: "Aug '25", overallAvg: 62 },
  { month: "Sep '25", overallAvg: 62.8 },
  { month: "Oct '25", overallAvg: 63.5 },
  { month: "Nov '25", overallAvg: 64 },
  { month: "Dec '25", overallAvg: 65 },
  { month: "Jan '26", overallAvg: 65.8 },
  { month: "Feb '26", overallAvg: 66.5 },
  { month: "Mar '26", overallAvg: 67.2 },
  { month: "Apr '26", overallAvg: 68 },
  { month: "May '26", overallAvg: 69 },
];

export const ACTIVITIES: Record<string, ActivityEntry[]> = {
  westlands: [
    { id: "act1", zoneId: "westlands", kind: "road", text: "Waiyaki Way Phase 2 paving completed ahead of schedule", source: "KeNHA", createdAt: "2026-05-22T08:00:00Z" },
    { id: "act2", zoneId: "westlands", kind: "grid", text: "Smart meter rollout reached 1,200 units in Parklands", source: "KPLC", createdAt: "2026-05-20T14:30:00Z" },
    { id: "act3", zoneId: "westlands", kind: "esia", text: "Updated ESIA for Westlands commercial zone published", source: "NEMA", createdAt: "2026-05-18T10:00:00Z" },
    { id: "act4", zoneId: "westlands", kind: "density", text: "Population density survey updated for Q1 2026", source: "KNBS", createdAt: "2026-05-15T09:00:00Z" },
  ],
  starehe: [
    { id: "act5", zoneId: "starehe", kind: "road", text: "Inner Ring contractor issued show-cause notice", source: "KURA", createdAt: "2026-05-20T09:30:00Z" },
    { id: "act6", zoneId: "starehe", kind: "grid", text: "Fibre backbone extended to CBD junction", source: "ICTA", createdAt: "2026-05-16T11:00:00Z" },
  ],
  "embakasi-east": [
    { id: "act7", zoneId: "embakasi-east", kind: "grid", text: "Substation transformer testing completed successfully", source: "KETRACO", createdAt: "2026-05-21T15:00:00Z" },
    { id: "act8", zoneId: "embakasi-east", kind: "road", text: "Access road to substation graded", source: "KURA", createdAt: "2026-05-19T10:00:00Z" },
  ],
  kibra: [
    { id: "act9", zoneId: "kibra", kind: "water", text: "Communal water-kiosk borehole yield test returned 8.4 m³/hr — below projection", source: "NCWSC", createdAt: "2026-05-23T08:45:00Z" },
    { id: "act10", zoneId: "kibra", kind: "water", text: "Decentralized sanitation feasibility study entered review", source: "Athi Water Works", createdAt: "2026-05-19T13:00:00Z" },
    { id: "act11", zoneId: "kibra", kind: "road", text: "Kibra Access Roads community engagement phase signed off", source: "KURA", createdAt: "2026-05-14T09:30:00Z" },
  ],
  mathare: [
    { id: "act12", zoneId: "mathare", kind: "water", text: "DEWATS sanitation block siting confirmed above the flood line", source: "Athi Water Works", createdAt: "2026-05-20T11:15:00Z" },
    { id: "act13", zoneId: "mathare", kind: "water", text: "Baseline survey: 11% of households have safely-managed sanitation", source: "NCWSC", createdAt: "2026-05-18T10:00:00Z" },
    { id: "act14", zoneId: "mathare", kind: "esia", text: "Distribution Line ESIA published on the NEMA portal", source: "NEMA", createdAt: "2026-05-15T11:00:00Z" },
  ],
  "dagoretti-south": [
    { id: "act15", zoneId: "dagoretti-south", kind: "water", text: "Water-main trench flooding halted DN300 pipe laying at 58%", source: "NCWSC", createdAt: "2026-05-17T15:30:00Z" },
    { id: "act16", zoneId: "dagoretti-south", kind: "water", text: "Trenching completed across 6.2 km of the extension route", source: "NCWSC", createdAt: "2026-05-06T09:00:00Z" },
  ],
  "embakasi-south": [
    { id: "act17", zoneId: "embakasi-south", kind: "esia", text: "Faecal Sludge Treatment Plant ESIA opened for public participation", source: "NEMA", createdAt: "2026-05-21T12:00:00Z" },
    { id: "act18", zoneId: "embakasi-south", kind: "water", text: "Athi Water co-financing agreement unlocked KES 210M for sanitation", source: "Athi Water Works", createdAt: "2026-05-14T11:30:00Z" },
  ],
  ruaraka: [
    { id: "act19", zoneId: "ruaraka", kind: "road", text: "Bypass rehabilitation culvert and drainage works completed", source: "KURA", createdAt: "2026-05-13T14:00:00Z" },
  ],
  "dagoretti-north": [
    { id: "act20", zoneId: "dagoretti-north", kind: "grid", text: "Fibre-ring duct and manhole works completed on schedule", source: "ICTA", createdAt: "2026-05-11T10:30:00Z" },
  ],
};

export const METHODOLOGY: PillarDef[] = [
  {
    key: "social",
    name: "Social Wellbeing & Human Capital",
    description: "Whether the local population is thriving. A low score predicts future labour issues or shortage of skilled operators.",
    subMetrics: [
      { key: "spi", label: "Social Progress Index", description: "Basic medical care, access to amenities, and inclusiveness" },
      { key: "workforce", label: "Workforce Mobility Score", description: "How easily labour and specialized roles can move in and out" },
      { key: "livability", label: "Mental Health & Livability", description: "Access to green space, air quality, projected burnout" },
    ],
  },
  {
    key: "safety",
    name: "Safety & Security",
    description: "Freedom from physical, legal, and digital threats that could disrupt projects.",
    subMetrics: [
      { key: "ruleOfLaw", label: "Rule of Law Stability", description: "Probability of contract expropriation, five-year judicial independence trend" },
      { key: "physSecurity", label: "Infrastructure Physical Security", description: "Conflict heatmap, proximity to unrest or high-crime corridors" },
      { key: "digitalSov", label: "Digital Sovereignty & Cybersecurity", description: "Internet Freedom Score, network outage frequency" },
    ],
  },
  {
    key: "density",
    name: "Density & Scaling Dynamics",
    description: "Whether the region's density supports growth or constrains it.",
    subMetrics: [
      { key: "optDensity", label: "Optimal Density Ratio", description: "Infrastructure Capacity / Population Density. Low ratio flags over-saturation" },
      { key: "urbanFriction", label: "Urban Friction Index", description: "Average transit times for heavy equipment, zoning complexity" },
    ],
  },
  {
    key: "infra",
    name: "Infrastructure & Environmental Safeguards",
    description: "Whether documentation and legal architecture exist to back up large projects.",
    subMetrics: [
      { key: "esia", label: "ESIA Transparency", description: "Are Environmental and Social Impact Assessments publicly available" },
      { key: "sovImmunity", label: "Sovereign Immunity Risk", description: "Government accountability for breaches of infrastructure contracts" },
      { key: "resourceSov", label: "Resource Sovereignty", description: "Legal protections on water and energy rights" },
      { key: "waste", label: "Waste & Lifecycle Mandates", description: "Extended Producer Responsibility laws, decommissioning liabilities" },
      { key: "circular", label: "Circular Economy Freedom", description: "Whether laws permit reuse of greywater and recycled construction materials" },
    ],
  },
];
