#!/usr/bin/env node
// Generates the per-language pillar registries from pillars.json.
//
//   node scripts/gen-pillars.mjs           write the artefacts
//   node scripts/gen-pillars.mjs --check   exit 1 if any is stale
//
// The three languages cannot import one file, so they import three files
// derived from one. --check runs in CI so they cannot drift apart.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = join(root, "pillars.json");
const registry = JSON.parse(readFileSync(sourcePath, "utf8"));

const banner = (comment) =>
  [
    `${comment} Generated by scripts/gen-pillars.mjs from pillars.json.`,
    `${comment} Do not edit. Edit pillars.json and re-run the generator.`,
  ].join("\n");

const active = registry.pillars.filter((p) => p.status !== "off");
const off = registry.pillars.filter((p) => p.status === "off");

const totalWeight = active.reduce((sum, p) => sum + p.weight, 0);
if (Math.abs(totalWeight - 1) > 1e-9) {
  throw new Error(
    `Weights across non-off pillars must sum to 1, got ${totalWeight}. ` +
      `Held pillars carry weight 0 by design; check pillars.json.`,
  );
}

const phpValue = (v) => {
  if (v === null) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
};

const php = () => {
  const entry = (p) => {
    const lines = [
      `        'key' => ${phpValue(p.key)},`,
      `        'display_name' => ${phpValue(p.display_name)},`,
      `        'status' => ${phpValue(p.status)},`,
      `        'method' => ${phpValue(p.method)},`,
      `        'granularity' => ${phpValue(p.granularity ?? null)},`,
      `        'source_id' => ${phpValue(p.source_id ?? null)},`,
      `        'vintage' => ${phpValue(p.vintage ?? null)},`,
      `        'weight' => ${phpValue(p.weight)},`,
    ];
    if (p.description) {
      lines.splice(2, 0, `        'description' => ${phpValue(p.description)},`);
    }
    return `    [\n${lines.join("\n")}\n    ],`;
  };

  return `<?php

declare(strict_types=1);

${banner("//")}

return [
    'version' => ${phpValue(registry.version)},
    'pillars' => [
${registry.pillars.map(entry).join("\n")}
    ],
];
`;
};

const ts = () => {
  const lit = (v) => (v === null || v === undefined ? "null" : JSON.stringify(v));
  const entry = (p) =>
    [
      "  {",
      `    key: ${lit(p.key)},`,
      `    displayName: ${lit(p.display_name)},`,
      ...(p.description ? [`    description: ${lit(p.description)},`] : []),
      `    status: ${lit(p.status)},`,
      `    method: ${lit(p.method)},`,
      `    granularity: ${lit(p.granularity ?? null)},`,
      `    sourceId: ${lit(p.source_id ?? null)},`,
      `    vintage: ${lit(p.vintage ?? null)},`,
      `    weight: ${p.weight},`,
      "  },",
    ].join("\n");

  return `${banner("//")}

export type PillarStatus = "active" | "held" | "off";
export type PillarMethod = "measured" | "proxy" | "gap";
export type Granularity = "subcounty" | "county" | "utility" | "national";

export interface PillarDef {
  key: string;
  displayName: string;
  description?: string;
  status: PillarStatus;
  method: PillarMethod;
  granularity: Granularity | null;
  sourceId: string | null;
  vintage: string | null;
  weight: number;
}

export const PILLAR_REGISTRY_VERSION = ${lit(registry.version)};

/** Every pillar ever declared, including the retired ones. */
const ALL_PILLARS: readonly PillarDef[] = [
${registry.pillars.map(entry).join("\n")}
] as const;

/**
 * The pillars the UI may render. Off pillars are filtered out here, once, so
 * no component has to remember to check status.
 */
export const PILLARS: readonly PillarDef[] = ALL_PILLARS.filter((p) => p.status !== "off");

export type PillarKey = ${active.map((p) => JSON.stringify(p.key)).join(" | ")};

/** Registry order. Iterate this for tables, charts, sliders and legends. */
export const PILLAR_KEYS: readonly PillarKey[] = PILLARS.map((p) => p.key as PillarKey);

export const RETIRED_PILLAR_KEYS: readonly string[] = [
${off.map((p) => `  ${lit(p.key)},`).join("\n")}
];

export const PILLARS_BY_KEY: Readonly<Record<PillarKey, PillarDef>> = Object.freeze(
  Object.fromEntries(PILLARS.map((p) => [p.key, p])),
) as Record<PillarKey, PillarDef>;

export function isPillarKey(value: string): value is PillarKey {
  return PILLARS.some((p) => p.key === value);
}
`;
};

const py = () => {
  const lit = (v) => (v === null || v === undefined ? "None" : JSON.stringify(v));
  const entry = (p) =>
    [
      "    PillarDef(",
      `        key=${lit(p.key)},`,
      `        display_name=${lit(p.display_name)},`,
      `        status=${lit(p.status)},`,
      `        method=${lit(p.method)},`,
      `        granularity=${lit(p.granularity ?? null)},`,
      `        source_id=${lit(p.source_id ?? null)},`,
      `        vintage=${lit(p.vintage ?? null)},`,
      `        weight=${p.weight},`,
      "    ),",
    ].join("\n");

  return `${banner("#")}
"""Pillar registry shared with the Laravel backend and the React frontend."""
from __future__ import annotations

from typing import Final, Literal, NamedTuple

PillarStatus = Literal["active", "held", "off"]
PillarMethod = Literal["measured", "proxy", "gap"]
Granularity = Literal["subcounty", "county", "utility", "national"]


class PillarDef(NamedTuple):
    key: str
    display_name: str
    status: PillarStatus
    method: PillarMethod
    granularity: Granularity | None
    source_id: str | None
    vintage: str | None
    weight: float


PILLAR_REGISTRY_VERSION: Final = ${lit(registry.version)}

ALL_PILLARS: Final[tuple[PillarDef, ...]] = (
${registry.pillars.map(entry).join("\n")}
)

#: The pillars anything downstream may act on. Off pillars are excluded here,
#: once, so no caller has to remember to check status.
PILLARS: Final[tuple[PillarDef, ...]] = tuple(p for p in ALL_PILLARS if p.status != "off")

PILLAR_KEYS: Final[frozenset[str]] = frozenset(p.key for p in PILLARS)

RETIRED_PILLAR_KEYS: Final[frozenset[str]] = frozenset(
    p.key for p in ALL_PILLARS if p.status == "off"
)

PILLARS_BY_KEY: Final[dict[str, PillarDef]] = {p.key: p for p in PILLARS}
`;
};

const targets = [
  { path: join(root, "nuvola-atlas-backend", "config", "pillars.php"), render: php },
  {
    path: join(root, "nuvola-atlas-frontend", "src", "lib", "pillars.generated.ts"),
    render: ts,
  },
  {
    path: join(root, "nuvola-atlas-ingestion", "app", "models", "pillars_generated.py"),
    render: py,
  },
];

const check = process.argv.includes("--check");
let stale = 0;

for (const { path, render } of targets) {
  const next = render();
  const rel = relative(root, path).replace(/\\/g, "/");

  if (check) {
    let current = null;
    try {
      current = readFileSync(path, "utf8");
    } catch {
      /* missing counts as stale */
    }
    if (current !== next) {
      console.error(`stale: ${rel}`);
      stale += 1;
    }
    continue;
  }

  writeFileSync(path, next);
  console.log(`wrote: ${rel}`);
}

if (check) {
  if (stale > 0) {
    console.error(`\n${stale} generated file(s) out of date. Run: node scripts/gen-pillars.mjs`);
    process.exit(1);
  }
  console.log("pillar registry is in sync");
}
