// Generated by scripts/gen-pillars.mjs from pillars.json.
// Do not edit. Edit pillars.json and re-run the generator.

export type PillarStatus = "active" | "held" | "off";
export type PillarMethod = "measured" | "proxy" | "gap";
export type Granularity = "subcounty" | "county" | "utility" | "national";

export interface PillarDef {
  key: string;
  displayName: string;
  description?: string;
  status: PillarStatus;
  method: PillarMethod;
  granularity: Granularity | null;
  sourceId: string | null;
  vintage: string | null;
  weight: number;
}

export const PILLAR_REGISTRY_VERSION = "2026-08-22";

/** Every pillar ever declared, including the retired ones. */
const ALL_PILLARS: readonly PillarDef[] = [
  {
    key: "water_sanitation",
    displayName: "Water & Sanitation",
    description: "Household water source and sanitation type, set against the utility's own service-performance record.",
    status: "active",
    method: "measured",
    granularity: "subcounty",
    sourceId: "knbs_census_2019",
    vintage: "2019 census",
    weight: 0.4,
  },
  {
    key: "road_density",
    displayName: "Road Density",
    description: "Kilometres of mapped road per square kilometre of sub-county.",
    status: "active",
    method: "measured",
    granularity: "subcounty",
    sourceId: "hot_osm_roads",
    vintage: "2026 extract",
    weight: 0.3,
  },
  {
    key: "transit_access",
    displayName: "Transit Access",
    description: "Share of residents living within walking distance of a matatu stop.",
    status: "active",
    method: "measured",
    granularity: "subcounty",
    sourceId: "digital_matatus_gtfs",
    vintage: "2026 extract",
    weight: 0.3,
  },
  {
    key: "electricity_access",
    displayName: "Electricity Access",
    description: "Share of households using electricity for lighting. The vintage is old and is stated on every reading.",
    status: "held",
    method: "measured",
    granularity: "subcounty",
    sourceId: "knbs_census_2019",
    vintage: "2019 census",
    weight: 0,
  },
  {
    key: "civic",
    displayName: "Civic & Governance",
    status: "off",
    method: "gap",
    granularity: null,
    sourceId: null,
    vintage: null,
    weight: 0,
  },
  {
    key: "safety",
    displayName: "Safety & Security",
    status: "off",
    method: "gap",
    granularity: null,
    sourceId: null,
    vintage: null,
    weight: 0,
  },
  {
    key: "project_momentum",
    displayName: "Project Momentum",
    status: "off",
    method: "gap",
    granularity: null,
    sourceId: null,
    vintage: null,
    weight: 0,
  },
  {
    key: "environment",
    displayName: "Environment",
    status: "off",
    method: "gap",
    granularity: null,
    sourceId: null,
    vintage: null,
    weight: 0,
  },
  {
    key: "smart_grid",
    displayName: "Smart Grid",
    status: "off",
    method: "gap",
    granularity: null,
    sourceId: null,
    vintage: null,
    weight: 0,
  },
] as const;

/**
 * The pillars the UI may render. Off pillars are filtered out here, once, so
 * no component has to remember to check status.
 */
export const PILLARS: readonly PillarDef[] = ALL_PILLARS.filter((p) => p.status !== "off");

export type PillarKey = "water_sanitation" | "road_density" | "transit_access" | "electricity_access";

/** Registry order. Iterate this for tables, charts, sliders and legends. */
export const PILLAR_KEYS: readonly PillarKey[] = PILLARS.map((p) => p.key as PillarKey);

export const RETIRED_PILLAR_KEYS: readonly string[] = [
  "civic",
  "safety",
  "project_momentum",
  "environment",
  "smart_grid",
];

export const PILLARS_BY_KEY: Readonly<Record<PillarKey, PillarDef>> = Object.freeze(
  Object.fromEntries(PILLARS.map((p) => [p.key, p])),
) as Record<PillarKey, PillarDef>;

export function isPillarKey(value: string): value is PillarKey {
  return PILLARS.some((p) => p.key === value);
}
