# Generated by scripts/gen-pillars.mjs from pillars.json.
# Do not edit. Edit pillars.json and re-run the generator.
"""Pillar registry shared with the Laravel backend and the React frontend."""
from __future__ import annotations

from typing import Final, Literal, NamedTuple

PillarStatus = Literal["active", "held", "off"]
PillarMethod = Literal["measured", "proxy", "gap"]
Granularity = Literal["subcounty", "county", "utility", "national"]


class PillarDef(NamedTuple):
    key: str
    display_name: str
    status: PillarStatus
    method: PillarMethod
    granularity: Granularity | None
    source_id: str | None
    vintage: str | None
    weight: float


PILLAR_REGISTRY_VERSION: Final = "2026-08-22"

ALL_PILLARS: Final[tuple[PillarDef, ...]] = (
    PillarDef(
        key="water_sanitation",
        display_name="Water & Sanitation",
        status="active",
        method="measured",
        granularity="subcounty",
        source_id="knbs_census_2019",
        vintage="2019 census",
        weight=0.4,
    ),
    PillarDef(
        key="road_density",
        display_name="Road Density",
        status="active",
        method="measured",
        granularity="subcounty",
        source_id="hot_osm_roads",
        vintage="2026 extract",
        weight=0.3,
    ),
    PillarDef(
        key="transit_access",
        display_name="Transit Access",
        status="active",
        method="measured",
        granularity="subcounty",
        source_id="digital_matatus_gtfs",
        vintage="2026 extract",
        weight=0.3,
    ),
    PillarDef(
        key="electricity_access",
        display_name="Electricity Access",
        status="held",
        method="measured",
        granularity="subcounty",
        source_id="knbs_census_2019",
        vintage="2019 census",
        weight=0,
    ),
    PillarDef(
        key="civic_index",
        display_name="Civic Participation",
        status="off",
        method="gap",
        granularity=None,
        source_id=None,
        vintage=None,
        weight=0,
    ),
    PillarDef(
        key="safety",
        display_name="Safety & Security",
        status="off",
        method="gap",
        granularity=None,
        source_id=None,
        vintage=None,
        weight=0,
    ),
    PillarDef(
        key="project_momentum",
        display_name="Project Momentum",
        status="off",
        method="gap",
        granularity=None,
        source_id=None,
        vintage=None,
        weight=0,
    ),
    PillarDef(
        key="environment",
        display_name="Environment",
        status="off",
        method="gap",
        granularity=None,
        source_id=None,
        vintage=None,
        weight=0,
    ),
    PillarDef(
        key="smart_grid",
        display_name="Smart Grid",
        status="off",
        method="gap",
        granularity=None,
        source_id=None,
        vintage=None,
        weight=0,
    ),
)

#: The pillars anything downstream may act on. Off pillars are excluded here,
#: once, so no caller has to remember to check status.
PILLARS: Final[tuple[PillarDef, ...]] = tuple(p for p in ALL_PILLARS if p.status != "off")

PILLAR_KEYS: Final[frozenset[str]] = frozenset(p.key for p in PILLARS)

RETIRED_PILLAR_KEYS: Final[frozenset[str]] = frozenset(
    p.key for p in ALL_PILLARS if p.status == "off"
)

PILLARS_BY_KEY: Final[dict[str, PillarDef]] = {p.key: p for p in PILLARS}
